config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  get "/users/:id", to: "users#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#index'
  # get "/questions", to: "questions#index"
  # get "/questions/new", to: "questions#new"
  # post "/questions", to: "questions#create"
  # get "/questions/:id", to: "questions#show"

  # get "/questions/:id/edit", to: "questions#edit"
  # patch "/questions/:id", to: "questions#update"
  # delete "/questions/:id", to: "questions#destroy"
  resources :questions do
    resource :answers, only: [:create, :edit, :update]
  end
  
  resources :articles do
    collection do
      get 'search' => 'articles#search'
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
   belongs_to :user
   has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, length: { maximum: 3000 }


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]


  def index
    @test = "テストテキスト"
  end

  def show
    @question = Question.find(params[:id])
    @@answer = Answer.new
  end

  def new
    @question = Question.new
    # @test = "new_テストテキスト"
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    # @test = "create_テストテキスト"
    if @question.save
       flash[:notice] = "成功！"
      redirect_to("/questions/#{@question.id}")
    else
      flash.now[:alert] = "失敗！"
      render("questions/new")
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "成功！"
      redirect_to("/questions/#{@question.id}")
    else
      flash.now[:alert] = "失敗！"
      render("questions/edit")
    end
  end


  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "成功！"
    redirect_to("/questions")
  end

  private
    def question_params
      params.require(:question).permit(:title, :body)
    end
    
    def ensure_correct_user
      @question = Question.find_by(id: params[:id])
      if @question.user_id != current_user.id
        flash[:alert] = "権限がありません"
        redirect_to("/questions/#{@question.id}")
      end
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<%= form_with(model: @question, local: true) do |f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body, "本文" %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<%= @test %>

<%#= link_to 'ゲストログイン（閲覧用）', homes_guest_sign_in_path, method: :post %>

<%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>

app/views/questions/new.html.erb
<%= form_with(model: @question, local: true) do |f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>
  <div>
     <%= f.label :body, "本文" %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

<!--<div>-->
<!--  <%#= @test %>-->
<!--</div>-->

app/views/questions/show.html.erb
<p><%= @question.title %></p>
<p><%= @question.body %></p>

<%= link_to("編集", "/questions/#{@question.id}/edit") %>
<%= link_to("削除", "/questions/#{@question.id}", method: :delete, data: {confirm: "本当に削除しますか？"}) %>

<div>
  <%= form_with(model: [@question, @answer], local: true) do |f| %>
  <%#= form_with(model: @answer, local: true) do |f| %>
    <div>
      <%= f.label :body, "回答" %><br>
      <%= f.text_area :body %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

<hr>
<div>
  <% @question.answers.each do |answer| %>
    <p><%= answer.body %></p>
  <% end %>
</div>